### ISSUE TITLE
License Copyright Notice

### ISSUE THREAD

**Issue by rktjmp** [moiristo/tileup#1]
Hello Reinier, thank you for improving `tileup` while I have been unable to!

While I was viewing your changes, I noticed you removed my name from the copyright notice. 

https://github.com/moiristo/tileup/commit/cc711ccef731f68574df090893f3211689697217#diff-52403e362cffe8078bbe57d9985be27a

I would appreciate it if you could restore my name to the license file while  also appending yours. 

```
Copyright (c) 2013 Oliver Marriott
Copyright (c) 2017 Reinier de Lange
```

While the MIT license allows for extension, modification, etc. of the code, I do retain the copyright of what I've written and as per the license, it should remain included:

> The above copyright notice and this permission notice shall be
> included in all copies or substantial portions of the Software.

I can not make you do this but I would hope that as a member of the open source community you will understand the importance of attribution in collaboration.

**Comment by moiristo** [comment]
Hello Oliver,

I do understand the importance of attribution in collaboration, that's why I opened a PR back in 2017. Unfortunately I didn't get any response, so I decided to create a release of my own fork. As your contribution to this fork is relatively small, my suggestion is to update the license as explained [here](https://softwareengineering.stackexchange.com/questions/277688/if-i-fork-a-project-on-github-that-is-licensed-under-mit-how-to-i-handle-the-at). Do you agree?

**Comment by rktjmp** [comment]
Sorry I was unable to respond to the PR, I was dead for a time. I know it's frustrating to have PR's go unanswered, effort ignored and projects left to rot.

Something in the style you linked is totally fine, 

> Copyright for portions of project Foo are held by [original author, year] as part of project Bar. All other copyright for project Foo are held by [your name, year].

**Comment by moiristo** [comment]
Alright, I have updated the license in the `develop` branch. If everything is ok, I'll merge to master.
